// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cdpb.proto

package cdpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	base "github.com/tommenx/cdproto/base"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//存储设备的类型
type StorageType int32

const (
	StorageType_NVM StorageType = 0
	StorageType_SSD StorageType = 1
	StorageType_HDD StorageType = 2
)

var StorageType_name = map[int32]string{
	0: "NVM",
	1: "SSD",
	2: "HDD",
}

var StorageType_value = map[string]int32{
	"NVM": 0,
	"SSD": 1,
	"HDD": 2,
}

func (x StorageType) String() string {
	return proto.EnumName(StorageType_name, int32(x))
}

func (StorageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{0}
}

//资源的种类
type ResourceType int32

const (
	ResourceType_ReadBps      ResourceType = 0
	ResourceType_ReadIops     ResourceType = 1
	ResourceType_WriteBps     ResourceType = 2
	ResourceType_WriteIops    ResourceType = 3
	ResourceType_StorageSpace ResourceType = 4
)

var ResourceType_name = map[int32]string{
	0: "ReadBps",
	1: "ReadIops",
	2: "WriteBps",
	3: "WriteIops",
	4: "StorageSpace",
}

var ResourceType_value = map[string]int32{
	"ReadBps":      0,
	"ReadIops":     1,
	"WriteBps":     2,
	"WriteIops":    3,
	"StorageSpace": 4,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}

func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{1}
}

type Resource struct {
	ResourceType         ResourceType `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3,enum=cdpb.ResourceType" json:"resource_type,omitempty"`
	Size                 int64        `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{0}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetResourceType() ResourceType {
	if m != nil {
		return m.ResourceType
	}
	return ResourceType_ReadBps
}

func (m *Resource) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type NodeStorage struct {
	NodeName             string     `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Storage              []*Storage `protobuf:"bytes,2,rep,name=storage,proto3" json:"storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NodeStorage) Reset()         { *m = NodeStorage{} }
func (m *NodeStorage) String() string { return proto.CompactTextString(m) }
func (*NodeStorage) ProtoMessage()    {}
func (*NodeStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{1}
}

func (m *NodeStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStorage.Unmarshal(m, b)
}
func (m *NodeStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStorage.Marshal(b, m, deterministic)
}
func (m *NodeStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStorage.Merge(m, src)
}
func (m *NodeStorage) XXX_Size() int {
	return xxx_messageInfo_NodeStorage.Size(m)
}
func (m *NodeStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStorage.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStorage proto.InternalMessageInfo

func (m *NodeStorage) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeStorage) GetStorage() []*Storage {
	if m != nil {
		return m.Storage
	}
	return nil
}

//对于存储资源的单位默认为G
//对于磁盘的默认单位为MB
type Storage struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StorageType          StorageType          `protobuf:"varint,2,opt,name=storage_type,json=storageType,proto3,enum=cdpb.StorageType" json:"storage_type,omitempty"`
	Resource             map[string]*Resource `protobuf:"bytes,3,rep,name=resource,proto3" json:"resource,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Storage) Reset()         { *m = Storage{} }
func (m *Storage) String() string { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()    {}
func (*Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{2}
}

func (m *Storage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storage.Unmarshal(m, b)
}
func (m *Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storage.Marshal(b, m, deterministic)
}
func (m *Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storage.Merge(m, src)
}
func (m *Storage) XXX_Size() int {
	return xxx_messageInfo_Storage.Size(m)
}
func (m *Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Storage proto.InternalMessageInfo

func (m *Storage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Storage) GetStorageType() StorageType {
	if m != nil {
		return m.StorageType
	}
	return StorageType_NVM
}

func (m *Storage) GetResource() map[string]*Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type PodResource struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string               `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Node                 string               `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	RequestResource      map[string]*Resource `protobuf:"bytes,4,rep,name=request_resource,json=requestResource,proto3" json:"request_resource,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PodResource) Reset()         { *m = PodResource{} }
func (m *PodResource) String() string { return proto.CompactTextString(m) }
func (*PodResource) ProtoMessage()    {}
func (*PodResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{3}
}

func (m *PodResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodResource.Unmarshal(m, b)
}
func (m *PodResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodResource.Marshal(b, m, deterministic)
}
func (m *PodResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodResource.Merge(m, src)
}
func (m *PodResource) XXX_Size() int {
	return xxx_messageInfo_PodResource.Size(m)
}
func (m *PodResource) XXX_DiscardUnknown() {
	xxx_messageInfo_PodResource.DiscardUnknown(m)
}

var xxx_messageInfo_PodResource proto.InternalMessageInfo

func (m *PodResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodResource) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodResource) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *PodResource) GetRequestResource() map[string]*Resource {
	if m != nil {
		return m.RequestResource
	}
	return nil
}

type Volume struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VolumeGroup          string   `protobuf:"bytes,2,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Maj                  string   `protobuf:"bytes,4,opt,name=maj,proto3" json:"maj,omitempty"`
	Min                  string   `protobuf:"bytes,5,opt,name=min,proto3" json:"min,omitempty"`
	LogicalVolume        string   `protobuf:"bytes,6,opt,name=logical_volume,json=logicalVolume,proto3" json:"logical_volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{4}
}

func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (m *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(m, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Volume) GetVolumeGroup() string {
	if m != nil {
		return m.VolumeGroup
	}
	return ""
}

func (m *Volume) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Volume) GetMaj() string {
	if m != nil {
		return m.Maj
	}
	return ""
}

func (m *Volume) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *Volume) GetLogicalVolume() string {
	if m != nil {
		return m.LogicalVolume
	}
	return ""
}

type PutNodeStorageRequest struct {
	Node                 *NodeStorage `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Base                 *base.Base   `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PutNodeStorageRequest) Reset()         { *m = PutNodeStorageRequest{} }
func (m *PutNodeStorageRequest) String() string { return proto.CompactTextString(m) }
func (*PutNodeStorageRequest) ProtoMessage()    {}
func (*PutNodeStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{5}
}

func (m *PutNodeStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutNodeStorageRequest.Unmarshal(m, b)
}
func (m *PutNodeStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutNodeStorageRequest.Marshal(b, m, deterministic)
}
func (m *PutNodeStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutNodeStorageRequest.Merge(m, src)
}
func (m *PutNodeStorageRequest) XXX_Size() int {
	return xxx_messageInfo_PutNodeStorageRequest.Size(m)
}
func (m *PutNodeStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutNodeStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutNodeStorageRequest proto.InternalMessageInfo

func (m *PutNodeStorageRequest) GetNode() *NodeStorage {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *PutNodeStorageRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type PutNodeStorageResponse struct {
	BaseResp             *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutNodeStorageResponse) Reset()         { *m = PutNodeStorageResponse{} }
func (m *PutNodeStorageResponse) String() string { return proto.CompactTextString(m) }
func (*PutNodeStorageResponse) ProtoMessage()    {}
func (*PutNodeStorageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{6}
}

func (m *PutNodeStorageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutNodeStorageResponse.Unmarshal(m, b)
}
func (m *PutNodeStorageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutNodeStorageResponse.Marshal(b, m, deterministic)
}
func (m *PutNodeStorageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutNodeStorageResponse.Merge(m, src)
}
func (m *PutNodeStorageResponse) XXX_Size() int {
	return xxx_messageInfo_PutNodeStorageResponse.Size(m)
}
func (m *PutNodeStorageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutNodeStorageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutNodeStorageResponse proto.InternalMessageInfo

func (m *PutNodeStorageResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetNodeStorageRequest struct {
	Base                 *base.Base `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetNodeStorageRequest) Reset()         { *m = GetNodeStorageRequest{} }
func (m *GetNodeStorageRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeStorageRequest) ProtoMessage()    {}
func (*GetNodeStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{7}
}

func (m *GetNodeStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStorageRequest.Unmarshal(m, b)
}
func (m *GetNodeStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStorageRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStorageRequest.Merge(m, src)
}
func (m *GetNodeStorageRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeStorageRequest.Size(m)
}
func (m *GetNodeStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStorageRequest proto.InternalMessageInfo

func (m *GetNodeStorageRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type GetNodeStorageResponse struct {
	NodeMap              map[string]*NodeStorage `protobuf:"bytes,1,rep,name=node_map,json=nodeMap,proto3" json:"node_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BaseResp             *base.BaseResp          `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetNodeStorageResponse) Reset()         { *m = GetNodeStorageResponse{} }
func (m *GetNodeStorageResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeStorageResponse) ProtoMessage()    {}
func (*GetNodeStorageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{8}
}

func (m *GetNodeStorageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStorageResponse.Unmarshal(m, b)
}
func (m *GetNodeStorageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStorageResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeStorageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStorageResponse.Merge(m, src)
}
func (m *GetNodeStorageResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeStorageResponse.Size(m)
}
func (m *GetNodeStorageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStorageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStorageResponse proto.InternalMessageInfo

func (m *GetNodeStorageResponse) GetNodeMap() map[string]*NodeStorage {
	if m != nil {
		return m.NodeMap
	}
	return nil
}

func (m *GetNodeStorageResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type PutPodResourceRequest struct {
	Pod                  *PodResource `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Base                 *base.Base   `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PutPodResourceRequest) Reset()         { *m = PutPodResourceRequest{} }
func (m *PutPodResourceRequest) String() string { return proto.CompactTextString(m) }
func (*PutPodResourceRequest) ProtoMessage()    {}
func (*PutPodResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{9}
}

func (m *PutPodResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPodResourceRequest.Unmarshal(m, b)
}
func (m *PutPodResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPodResourceRequest.Marshal(b, m, deterministic)
}
func (m *PutPodResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPodResourceRequest.Merge(m, src)
}
func (m *PutPodResourceRequest) XXX_Size() int {
	return xxx_messageInfo_PutPodResourceRequest.Size(m)
}
func (m *PutPodResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPodResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutPodResourceRequest proto.InternalMessageInfo

func (m *PutPodResourceRequest) GetPod() *PodResource {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (m *PutPodResourceRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type PutPodResourceResponse struct {
	BaseResp             *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutPodResourceResponse) Reset()         { *m = PutPodResourceResponse{} }
func (m *PutPodResourceResponse) String() string { return proto.CompactTextString(m) }
func (*PutPodResourceResponse) ProtoMessage()    {}
func (*PutPodResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{10}
}

func (m *PutPodResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPodResourceResponse.Unmarshal(m, b)
}
func (m *PutPodResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPodResourceResponse.Marshal(b, m, deterministic)
}
func (m *PutPodResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPodResourceResponse.Merge(m, src)
}
func (m *PutPodResourceResponse) XXX_Size() int {
	return xxx_messageInfo_PutPodResourceResponse.Size(m)
}
func (m *PutPodResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPodResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutPodResourceResponse proto.InternalMessageInfo

func (m *PutPodResourceResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type PutVolumeRequest struct {
	Volume               *Volume    `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Base                 *base.Base `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutVolumeRequest) Reset()         { *m = PutVolumeRequest{} }
func (m *PutVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*PutVolumeRequest) ProtoMessage()    {}
func (*PutVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{11}
}

func (m *PutVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutVolumeRequest.Unmarshal(m, b)
}
func (m *PutVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutVolumeRequest.Marshal(b, m, deterministic)
}
func (m *PutVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutVolumeRequest.Merge(m, src)
}
func (m *PutVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_PutVolumeRequest.Size(m)
}
func (m *PutVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutVolumeRequest proto.InternalMessageInfo

func (m *PutVolumeRequest) GetVolume() *Volume {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *PutVolumeRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type PutVolumeResponse struct {
	BaseResp             *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutVolumeResponse) Reset()         { *m = PutVolumeResponse{} }
func (m *PutVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*PutVolumeResponse) ProtoMessage()    {}
func (*PutVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{12}
}

func (m *PutVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutVolumeResponse.Unmarshal(m, b)
}
func (m *PutVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutVolumeResponse.Marshal(b, m, deterministic)
}
func (m *PutVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutVolumeResponse.Merge(m, src)
}
func (m *PutVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_PutVolumeResponse.Size(m)
}
func (m *PutVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutVolumeResponse proto.InternalMessageInfo

func (m *PutVolumeResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func init() {
	proto.RegisterEnum("cdpb.StorageType", StorageType_name, StorageType_value)
	proto.RegisterEnum("cdpb.ResourceType", ResourceType_name, ResourceType_value)
	proto.RegisterType((*Resource)(nil), "cdpb.Resource")
	proto.RegisterType((*NodeStorage)(nil), "cdpb.NodeStorage")
	proto.RegisterType((*Storage)(nil), "cdpb.Storage")
	proto.RegisterMapType((map[string]*Resource)(nil), "cdpb.Storage.ResourceEntry")
	proto.RegisterType((*PodResource)(nil), "cdpb.PodResource")
	proto.RegisterMapType((map[string]*Resource)(nil), "cdpb.PodResource.RequestResourceEntry")
	proto.RegisterType((*Volume)(nil), "cdpb.Volume")
	proto.RegisterType((*PutNodeStorageRequest)(nil), "cdpb.PutNodeStorageRequest")
	proto.RegisterType((*PutNodeStorageResponse)(nil), "cdpb.PutNodeStorageResponse")
	proto.RegisterType((*GetNodeStorageRequest)(nil), "cdpb.GetNodeStorageRequest")
	proto.RegisterType((*GetNodeStorageResponse)(nil), "cdpb.GetNodeStorageResponse")
	proto.RegisterMapType((map[string]*NodeStorage)(nil), "cdpb.GetNodeStorageResponse.NodeMapEntry")
	proto.RegisterType((*PutPodResourceRequest)(nil), "cdpb.PutPodResourceRequest")
	proto.RegisterType((*PutPodResourceResponse)(nil), "cdpb.PutPodResourceResponse")
	proto.RegisterType((*PutVolumeRequest)(nil), "cdpb.PutVolumeRequest")
	proto.RegisterType((*PutVolumeResponse)(nil), "cdpb.PutVolumeResponse")
}

func init() { proto.RegisterFile("cdpb.proto", fileDescriptor_2b30a5d99d91ba1a) }

var fileDescriptor_2b30a5d99d91ba1a = []byte{
	// 791 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xed, 0x4e, 0x13, 0x4b,
	0x18, 0x66, 0xdb, 0xd2, 0x8f, 0x77, 0xb7, 0x3d, 0xcb, 0xe4, 0xc0, 0xd9, 0x14, 0x12, 0xa0, 0x07,
	0x0e, 0x3d, 0xc4, 0x94, 0xa4, 0x9a, 0x40, 0x8c, 0x7f, 0xc4, 0x2a, 0x1a, 0x02, 0xc1, 0xad, 0x01,
	0x35, 0x31, 0xcd, 0xb4, 0x3b, 0xa9, 0x8b, 0xdd, 0x9d, 0x75, 0x3f, 0x88, 0xf5, 0x62, 0xbc, 0x08,
	0xef, 0xc6, 0x78, 0x27, 0xfe, 0xd1, 0xcc, 0xc7, 0x96, 0x59, 0x58, 0x83, 0xe2, 0xaf, 0xbe, 0xf3,
	0x7e, 0xcd, 0xf3, 0xcc, 0xfb, 0xcc, 0x6c, 0x01, 0x46, 0x4e, 0x30, 0xec, 0x04, 0x21, 0x8d, 0x29,
	0x2a, 0x31, 0xbb, 0x09, 0x43, 0x1c, 0x11, 0xe1, 0x69, 0x9d, 0x41, 0xd5, 0x26, 0x11, 0x4d, 0xc2,
	0x11, 0x41, 0xbb, 0x50, 0x0f, 0xa5, 0x3d, 0x88, 0xa7, 0x01, 0xb1, 0xb4, 0x35, 0xad, 0xdd, 0xe8,
	0xa2, 0x0e, 0xef, 0x90, 0xa6, 0xbd, 0x98, 0x06, 0xc4, 0x36, 0x42, 0x65, 0x85, 0x10, 0x94, 0x22,
	0xf7, 0x23, 0xb1, 0x0a, 0x6b, 0x5a, 0xbb, 0x68, 0x73, 0xbb, 0xd5, 0x07, 0xfd, 0x98, 0x3a, 0xa4,
	0x1f, 0xd3, 0x10, 0x8f, 0x09, 0x5a, 0x86, 0x9a, 0x4f, 0x1d, 0x32, 0xf0, 0xb1, 0x27, 0xfa, 0xd6,
	0xec, 0x2a, 0x73, 0x1c, 0x63, 0x8f, 0xa0, 0x2d, 0xa8, 0x44, 0x22, 0xcf, 0x2a, 0xac, 0x15, 0xdb,
	0x7a, 0xb7, 0x2e, 0xb6, 0x94, 0xc5, 0x76, 0x1a, 0x6d, 0x7d, 0xd1, 0xa0, 0x92, 0x76, 0x44, 0x50,
	0x52, 0x9a, 0x71, 0x1b, 0xdd, 0x03, 0x43, 0xa6, 0x0a, 0x02, 0x05, 0x4e, 0x60, 0x21, 0xd3, 0x8d,
	0xe3, 0xd7, 0xa3, 0xcb, 0x05, 0xda, 0x85, 0x6a, 0x4a, 0xc7, 0x2a, 0xf2, 0xfd, 0x97, 0x33, 0x15,
	0x33, 0xea, 0x8f, 0xfd, 0x38, 0x9c, 0xda, 0xb3, 0xe4, 0xe6, 0x21, 0xd4, 0x33, 0x21, 0x64, 0x42,
	0xf1, 0x1d, 0x99, 0x4a, 0x48, 0xcc, 0x44, 0x1b, 0x30, 0x7f, 0x81, 0x27, 0x89, 0x80, 0xa2, 0x77,
	0x1b, 0xd9, 0xb3, 0xb4, 0x45, 0xf0, 0x7e, 0x61, 0x4f, 0x6b, 0x7d, 0xd3, 0x40, 0x3f, 0xa1, 0xce,
	0x6c, 0x1a, 0x79, 0xfc, 0x56, 0xa0, 0xc6, 0x7e, 0xa3, 0x00, 0x8f, 0x44, 0xc7, 0x9a, 0x7d, 0xe9,
	0xe0, 0x15, 0xd4, 0x61, 0x1c, 0x44, 0x05, 0x75, 0x08, 0x7a, 0x0e, 0x66, 0x48, 0xde, 0x27, 0x24,
	0x8a, 0x07, 0x33, 0x8e, 0x25, 0xce, 0xf1, 0x3f, 0x01, 0x45, 0xd9, 0xb2, 0x63, 0x8b, 0xcc, 0x2c,
	0xdd, 0xbf, 0xc2, 0xac, 0xb7, 0x69, 0xc3, 0xdf, 0x79, 0x89, 0x7f, 0x44, 0xfe, 0x93, 0x06, 0xe5,
	0x53, 0x3a, 0x49, 0xbc, 0x7c, 0xde, 0xeb, 0x60, 0x5c, 0xf0, 0xe8, 0x60, 0x1c, 0xd2, 0x24, 0x90,
	0xd4, 0x75, 0xe1, 0x3b, 0x60, 0x2e, 0x56, 0x96, 0x24, 0xae, 0x93, 0x92, 0x67, 0x36, 0x43, 0xe4,
	0xe1, 0x73, 0xab, 0x24, 0x10, 0x79, 0xf8, 0x9c, 0x7b, 0x5c, 0xdf, 0x9a, 0x97, 0x1e, 0xd7, 0x47,
	0x9b, 0xd0, 0x98, 0xd0, 0xb1, 0x3b, 0xc2, 0x93, 0x81, 0x68, 0x67, 0x95, 0x79, 0xb0, 0x2e, 0xbd,
	0x02, 0x55, 0x6b, 0x00, 0x8b, 0x27, 0x49, 0xac, 0x28, 0x5a, 0x1e, 0x01, 0xda, 0x94, 0x87, 0xae,
	0x71, 0x8a, 0x52, 0x6a, 0x6a, 0x9e, 0x98, 0xc3, 0x2a, 0x94, 0xd8, 0xad, 0xb3, 0xbe, 0x8b, 0x3c,
	0xe8, 0xf0, 0x3b, 0xb8, 0x8f, 0x23, 0x62, 0xf3, 0x40, 0xeb, 0x09, 0x2c, 0x5d, 0xdd, 0x20, 0x0a,
	0xa8, 0x1f, 0x11, 0x74, 0x07, 0x6a, 0x2c, 0x83, 0xcd, 0x2f, 0x48, 0xeb, 0x1b, 0x4a, 0x3d, 0x89,
	0x02, 0xbb, 0x3a, 0x94, 0x56, 0x6b, 0x0f, 0x16, 0x0f, 0x48, 0x1e, 0xd0, 0x1b, 0x11, 0x7c, 0xd5,
	0x60, 0xe9, 0x6a, 0xa9, 0x84, 0xd0, 0x03, 0x7e, 0x59, 0x07, 0x1e, 0x0e, 0x2c, 0x8d, 0xab, 0xe7,
	0x7f, 0x41, 0x34, 0x3f, 0x9f, 0xf3, 0x3f, 0xc2, 0x81, 0x10, 0x50, 0xc5, 0x17, 0xab, 0xdf, 0x23,
	0xd2, 0x3c, 0x02, 0x43, 0x6d, 0x93, 0x23, 0xaf, 0xad, 0xac, 0xbc, 0x72, 0xce, 0x5e, 0x51, 0xd8,
	0x1b, 0x3e, 0x40, 0x45, 0xed, 0xe9, 0xb9, 0xfc, 0x0b, 0xc5, 0x80, 0x3a, 0xd9, 0xf9, 0xa9, 0x69,
	0x2c, 0xfa, 0xab, 0xe3, 0xcb, 0xb4, 0xbf, 0xd5, 0xf8, 0x5e, 0x81, 0x79, 0x92, 0xc4, 0x42, 0x74,
	0x29, 0xc2, 0x0d, 0x28, 0x4b, 0x69, 0x8a, 0x6a, 0x43, 0x80, 0x94, 0x49, 0x32, 0x76, 0x33, 0xc4,
	0x87, 0xb0, 0xa0, 0xb4, 0xbe, 0x0d, 0xba, 0xed, 0x36, 0xe8, 0xca, 0x2b, 0x8a, 0x2a, 0x50, 0x3c,
	0x3e, 0x3d, 0x32, 0xe7, 0x98, 0xd1, 0xef, 0xf7, 0x4c, 0x8d, 0x19, 0x4f, 0x7b, 0x3d, 0xb3, 0xb0,
	0xfd, 0x12, 0x0c, 0xf5, 0x83, 0x81, 0x74, 0xa8, 0xd8, 0x04, 0x3b, 0xfb, 0x41, 0x64, 0xce, 0x21,
	0x83, 0x7d, 0x74, 0xb0, 0xf3, 0x8c, 0x06, 0x91, 0xa9, 0xb1, 0xd5, 0x59, 0xe8, 0xc6, 0x84, 0xc5,
	0x0a, 0xa8, 0x0e, 0x35, 0xbe, 0xe2, 0xc1, 0x22, 0x32, 0xc1, 0x90, 0x3b, 0xf6, 0xd9, 0x1b, 0x67,
	0x96, 0xba, 0x9f, 0x0b, 0xa0, 0x3f, 0xa2, 0x34, 0x74, 0x5c, 0x1f, 0xc7, 0x34, 0x44, 0x87, 0xd0,
	0xc8, 0x5e, 0x1c, 0x24, 0x5f, 0xef, 0xdc, 0xfb, 0xda, 0x5c, 0xc9, 0x0f, 0xca, 0xe3, 0x38, 0x84,
	0x46, 0x56, 0xd2, 0x69, 0xb3, 0xdc, 0x3b, 0x95, 0x36, 0xfb, 0xc9, 0xad, 0x11, 0xc8, 0xd4, 0x37,
	0xfd, 0x12, 0xd9, 0x75, 0x21, 0x2a, 0xc8, 0xf2, 0x64, 0xf4, 0x00, 0x6a, 0xb3, 0xe9, 0xa1, 0xa5,
	0x59, 0x6a, 0x46, 0x29, 0xcd, 0x7f, 0xae, 0xf9, 0x45, 0xf5, 0xfe, 0xfa, 0xeb, 0xd5, 0xb1, 0x1b,
	0xbf, 0x4d, 0x86, 0x9d, 0x11, 0xf5, 0x76, 0x62, 0xea, 0x79, 0xc4, 0xff, 0xb0, 0x33, 0x72, 0xf8,
	0x9f, 0x00, 0xf6, 0x3b, 0x1c, 0x96, 0xb9, 0x7d, 0xf7, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f,
	0x4f, 0x6f, 0x69, 0x30, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoordinatorClient interface {
	PutNodeStorage(ctx context.Context, in *PutNodeStorageRequest, opts ...grpc.CallOption) (*PutNodeStorageResponse, error)
	GetNodeStorage(ctx context.Context, in *GetNodeStorageRequest, opts ...grpc.CallOption) (*GetNodeStorageResponse, error)
	PutPodResource(ctx context.Context, in *PutPodResourceRequest, opts ...grpc.CallOption) (*PutPodResourceResponse, error)
	PutVolume(ctx context.Context, in *PutVolumeRequest, opts ...grpc.CallOption) (*PutVolumeResponse, error)
}

type coordinatorClient struct {
	cc *grpc.ClientConn
}

func NewCoordinatorClient(cc *grpc.ClientConn) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) PutNodeStorage(ctx context.Context, in *PutNodeStorageRequest, opts ...grpc.CallOption) (*PutNodeStorageResponse, error) {
	out := new(PutNodeStorageResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/PutNodeStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) GetNodeStorage(ctx context.Context, in *GetNodeStorageRequest, opts ...grpc.CallOption) (*GetNodeStorageResponse, error) {
	out := new(GetNodeStorageResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/GetNodeStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) PutPodResource(ctx context.Context, in *PutPodResourceRequest, opts ...grpc.CallOption) (*PutPodResourceResponse, error) {
	out := new(PutPodResourceResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/PutPodResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) PutVolume(ctx context.Context, in *PutVolumeRequest, opts ...grpc.CallOption) (*PutVolumeResponse, error) {
	out := new(PutVolumeResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/PutVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
type CoordinatorServer interface {
	PutNodeStorage(context.Context, *PutNodeStorageRequest) (*PutNodeStorageResponse, error)
	GetNodeStorage(context.Context, *GetNodeStorageRequest) (*GetNodeStorageResponse, error)
	PutPodResource(context.Context, *PutPodResourceRequest) (*PutPodResourceResponse, error)
	PutVolume(context.Context, *PutVolumeRequest) (*PutVolumeResponse, error)
}

// UnimplementedCoordinatorServer can be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServer struct {
}

func (*UnimplementedCoordinatorServer) PutNodeStorage(ctx context.Context, req *PutNodeStorageRequest) (*PutNodeStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutNodeStorage not implemented")
}
func (*UnimplementedCoordinatorServer) GetNodeStorage(ctx context.Context, req *GetNodeStorageRequest) (*GetNodeStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeStorage not implemented")
}
func (*UnimplementedCoordinatorServer) PutPodResource(ctx context.Context, req *PutPodResourceRequest) (*PutPodResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPodResource not implemented")
}
func (*UnimplementedCoordinatorServer) PutVolume(ctx context.Context, req *PutVolumeRequest) (*PutVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutVolume not implemented")
}

func RegisterCoordinatorServer(s *grpc.Server, srv CoordinatorServer) {
	s.RegisterService(&_Coordinator_serviceDesc, srv)
}

func _Coordinator_PutNodeStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutNodeStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PutNodeStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/PutNodeStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PutNodeStorage(ctx, req.(*PutNodeStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_GetNodeStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetNodeStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/GetNodeStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetNodeStorage(ctx, req.(*GetNodeStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_PutPodResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPodResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PutPodResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/PutPodResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PutPodResource(ctx, req.(*PutPodResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_PutVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PutVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/PutVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PutVolume(ctx, req.(*PutVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coordinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cdpb.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutNodeStorage",
			Handler:    _Coordinator_PutNodeStorage_Handler,
		},
		{
			MethodName: "GetNodeStorage",
			Handler:    _Coordinator_GetNodeStorage_Handler,
		},
		{
			MethodName: "PutPodResource",
			Handler:    _Coordinator_PutPodResource_Handler,
		},
		{
			MethodName: "PutVolume",
			Handler:    _Coordinator_PutVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdpb.proto",
}
