// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cdpb.proto

package cdpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	base "github.com/tommenx/cdproto/base"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//对于存储资源的单位默认为G
//对于磁盘的默认单位为MB
type Storage struct {
	Level                string           `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Resource             map[string]int64 `protobuf:"bytes,3,rep,name=resource,proto3" json:"resource,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Storage) Reset()         { *m = Storage{} }
func (m *Storage) String() string { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()    {}
func (*Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{0}
}

func (m *Storage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storage.Unmarshal(m, b)
}
func (m *Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storage.Marshal(b, m, deterministic)
}
func (m *Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storage.Merge(m, src)
}
func (m *Storage) XXX_Size() int {
	return xxx_messageInfo_Storage.Size(m)
}
func (m *Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Storage proto.InternalMessageInfo

func (m *Storage) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Storage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Storage) GetResource() map[string]int64 {
	if m != nil {
		return m.Resource
	}
	return nil
}

type Node struct {
	Storage              []*Storage `protobuf:"bytes,1,rep,name=storage,proto3" json:"storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetStorage() []*Storage {
	if m != nil {
		return m.Storage
	}
	return nil
}

type PodResource struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string           `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Node                 string           `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	DockerId             string           `protobuf:"bytes,4,opt,name=dockerId,proto3" json:"dockerId,omitempty"`
	CgroupPath           string           `protobuf:"bytes,5,opt,name=cgroupPath,proto3" json:"cgroupPath,omitempty"`
	RequestResource      map[string]int64 `protobuf:"bytes,6,rep,name=request_resource,json=requestResource,proto3" json:"request_resource,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Level                string           `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PodResource) Reset()         { *m = PodResource{} }
func (m *PodResource) String() string { return proto.CompactTextString(m) }
func (*PodResource) ProtoMessage()    {}
func (*PodResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{2}
}

func (m *PodResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodResource.Unmarshal(m, b)
}
func (m *PodResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodResource.Marshal(b, m, deterministic)
}
func (m *PodResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodResource.Merge(m, src)
}
func (m *PodResource) XXX_Size() int {
	return xxx_messageInfo_PodResource.Size(m)
}
func (m *PodResource) XXX_DiscardUnknown() {
	xxx_messageInfo_PodResource.DiscardUnknown(m)
}

var xxx_messageInfo_PodResource proto.InternalMessageInfo

func (m *PodResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PodResource) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PodResource) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *PodResource) GetDockerId() string {
	if m != nil {
		return m.DockerId
	}
	return ""
}

func (m *PodResource) GetCgroupPath() string {
	if m != nil {
		return m.CgroupPath
	}
	return ""
}

func (m *PodResource) GetRequestResource() map[string]int64 {
	if m != nil {
		return m.RequestResource
	}
	return nil
}

func (m *PodResource) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

type Volume struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VolumeGroup          string   `protobuf:"bytes,2,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Maj                  string   `protobuf:"bytes,4,opt,name=maj,proto3" json:"maj,omitempty"`
	Min                  string   `protobuf:"bytes,5,opt,name=min,proto3" json:"min,omitempty"`
	LogicalVolume        string   `protobuf:"bytes,6,opt,name=logical_volume,json=logicalVolume,proto3" json:"logical_volume,omitempty"`
	Size                 int32    `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{3}
}

func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (m *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(m, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Volume) GetVolumeGroup() string {
	if m != nil {
		return m.VolumeGroup
	}
	return ""
}

func (m *Volume) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Volume) GetMaj() string {
	if m != nil {
		return m.Maj
	}
	return ""
}

func (m *Volume) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *Volume) GetLogicalVolume() string {
	if m != nil {
		return m.LogicalVolume
	}
	return ""
}

func (m *Volume) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type PutNodeStorageRequest struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 string     `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Node                 *Node      `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	Base                 *base.Base `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutNodeStorageRequest) Reset()         { *m = PutNodeStorageRequest{} }
func (m *PutNodeStorageRequest) String() string { return proto.CompactTextString(m) }
func (*PutNodeStorageRequest) ProtoMessage()    {}
func (*PutNodeStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{4}
}

func (m *PutNodeStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutNodeStorageRequest.Unmarshal(m, b)
}
func (m *PutNodeStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutNodeStorageRequest.Marshal(b, m, deterministic)
}
func (m *PutNodeStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutNodeStorageRequest.Merge(m, src)
}
func (m *PutNodeStorageRequest) XXX_Size() int {
	return xxx_messageInfo_PutNodeStorageRequest.Size(m)
}
func (m *PutNodeStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutNodeStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutNodeStorageRequest proto.InternalMessageInfo

func (m *PutNodeStorageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PutNodeStorageRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *PutNodeStorageRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *PutNodeStorageRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type PutNodeStorageResponse struct {
	BaseResp             *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutNodeStorageResponse) Reset()         { *m = PutNodeStorageResponse{} }
func (m *PutNodeStorageResponse) String() string { return proto.CompactTextString(m) }
func (*PutNodeStorageResponse) ProtoMessage()    {}
func (*PutNodeStorageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{5}
}

func (m *PutNodeStorageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutNodeStorageResponse.Unmarshal(m, b)
}
func (m *PutNodeStorageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutNodeStorageResponse.Marshal(b, m, deterministic)
}
func (m *PutNodeStorageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutNodeStorageResponse.Merge(m, src)
}
func (m *PutNodeStorageResponse) XXX_Size() int {
	return xxx_messageInfo_PutNodeStorageResponse.Size(m)
}
func (m *PutNodeStorageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutNodeStorageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutNodeStorageResponse proto.InternalMessageInfo

func (m *PutNodeStorageResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetNodeStorageRequest struct {
	Kind                 string     `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Node                 string     `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Base                 *base.Base `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetNodeStorageRequest) Reset()         { *m = GetNodeStorageRequest{} }
func (m *GetNodeStorageRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeStorageRequest) ProtoMessage()    {}
func (*GetNodeStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{6}
}

func (m *GetNodeStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStorageRequest.Unmarshal(m, b)
}
func (m *GetNodeStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStorageRequest.Marshal(b, m, deterministic)
}
func (m *GetNodeStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStorageRequest.Merge(m, src)
}
func (m *GetNodeStorageRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeStorageRequest.Size(m)
}
func (m *GetNodeStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStorageRequest proto.InternalMessageInfo

func (m *GetNodeStorageRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GetNodeStorageRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *GetNodeStorageRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type GetNodeStorageResponse struct {
	Nodes                map[string]*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BaseResp             *base.BaseResp   `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetNodeStorageResponse) Reset()         { *m = GetNodeStorageResponse{} }
func (m *GetNodeStorageResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeStorageResponse) ProtoMessage()    {}
func (*GetNodeStorageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{7}
}

func (m *GetNodeStorageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeStorageResponse.Unmarshal(m, b)
}
func (m *GetNodeStorageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeStorageResponse.Marshal(b, m, deterministic)
}
func (m *GetNodeStorageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeStorageResponse.Merge(m, src)
}
func (m *GetNodeStorageResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeStorageResponse.Size(m)
}
func (m *GetNodeStorageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeStorageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeStorageResponse proto.InternalMessageInfo

func (m *GetNodeStorageResponse) GetNodes() map[string]*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GetNodeStorageResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type PutPodResourceRequest struct {
	Pod                  *PodResource `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Operation            int32        `protobuf:"varint,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Base                 *base.Base   `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PutPodResourceRequest) Reset()         { *m = PutPodResourceRequest{} }
func (m *PutPodResourceRequest) String() string { return proto.CompactTextString(m) }
func (*PutPodResourceRequest) ProtoMessage()    {}
func (*PutPodResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{8}
}

func (m *PutPodResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPodResourceRequest.Unmarshal(m, b)
}
func (m *PutPodResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPodResourceRequest.Marshal(b, m, deterministic)
}
func (m *PutPodResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPodResourceRequest.Merge(m, src)
}
func (m *PutPodResourceRequest) XXX_Size() int {
	return xxx_messageInfo_PutPodResourceRequest.Size(m)
}
func (m *PutPodResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPodResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutPodResourceRequest proto.InternalMessageInfo

func (m *PutPodResourceRequest) GetPod() *PodResource {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (m *PutPodResourceRequest) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *PutPodResourceRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type PutPodResourceResponse struct {
	BaseResp             *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutPodResourceResponse) Reset()         { *m = PutPodResourceResponse{} }
func (m *PutPodResourceResponse) String() string { return proto.CompactTextString(m) }
func (*PutPodResourceResponse) ProtoMessage()    {}
func (*PutPodResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{9}
}

func (m *PutPodResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPodResourceResponse.Unmarshal(m, b)
}
func (m *PutPodResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPodResourceResponse.Marshal(b, m, deterministic)
}
func (m *PutPodResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPodResourceResponse.Merge(m, src)
}
func (m *PutPodResourceResponse) XXX_Size() int {
	return xxx_messageInfo_PutPodResourceResponse.Size(m)
}
func (m *PutPodResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPodResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutPodResourceResponse proto.InternalMessageInfo

func (m *PutPodResourceResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type PutVolumeRequest struct {
	Volume               *Volume    `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Pv                   string     `protobuf:"bytes,2,opt,name=pv,proto3" json:"pv,omitempty"`
	Operation            int32      `protobuf:"varint,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Base                 *base.Base `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutVolumeRequest) Reset()         { *m = PutVolumeRequest{} }
func (m *PutVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*PutVolumeRequest) ProtoMessage()    {}
func (*PutVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{10}
}

func (m *PutVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutVolumeRequest.Unmarshal(m, b)
}
func (m *PutVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutVolumeRequest.Marshal(b, m, deterministic)
}
func (m *PutVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutVolumeRequest.Merge(m, src)
}
func (m *PutVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_PutVolumeRequest.Size(m)
}
func (m *PutVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutVolumeRequest proto.InternalMessageInfo

func (m *PutVolumeRequest) GetVolume() *Volume {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *PutVolumeRequest) GetPv() string {
	if m != nil {
		return m.Pv
	}
	return ""
}

func (m *PutVolumeRequest) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *PutVolumeRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type PutVolumeResponse struct {
	BaseResp             *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutVolumeResponse) Reset()         { *m = PutVolumeResponse{} }
func (m *PutVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*PutVolumeResponse) ProtoMessage()    {}
func (*PutVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{11}
}

func (m *PutVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutVolumeResponse.Unmarshal(m, b)
}
func (m *PutVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutVolumeResponse.Marshal(b, m, deterministic)
}
func (m *PutVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutVolumeResponse.Merge(m, src)
}
func (m *PutVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_PutVolumeResponse.Size(m)
}
func (m *PutVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutVolumeResponse proto.InternalMessageInfo

func (m *PutVolumeResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetVolumeRequest struct {
	Namespace            string     `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Base                 *base.Base `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetVolumeRequest) Reset()         { *m = GetVolumeRequest{} }
func (m *GetVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*GetVolumeRequest) ProtoMessage()    {}
func (*GetVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{12}
}

func (m *GetVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumeRequest.Unmarshal(m, b)
}
func (m *GetVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumeRequest.Marshal(b, m, deterministic)
}
func (m *GetVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumeRequest.Merge(m, src)
}
func (m *GetVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_GetVolumeRequest.Size(m)
}
func (m *GetVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumeRequest proto.InternalMessageInfo

func (m *GetVolumeRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetVolumeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetVolumeRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type GetVolumeResponse struct {
	Volume               *Volume        `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	BaseResp             *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetVolumeResponse) Reset()         { *m = GetVolumeResponse{} }
func (m *GetVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*GetVolumeResponse) ProtoMessage()    {}
func (*GetVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{13}
}

func (m *GetVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumeResponse.Unmarshal(m, b)
}
func (m *GetVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumeResponse.Marshal(b, m, deterministic)
}
func (m *GetVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumeResponse.Merge(m, src)
}
func (m *GetVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_GetVolumeResponse.Size(m)
}
func (m *GetVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumeResponse proto.InternalMessageInfo

func (m *GetVolumeResponse) GetVolume() *Volume {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *GetVolumeResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetPodResourceRequest struct {
	Namespace            string     `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod                  string     `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Base                 *base.Base `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetPodResourceRequest) Reset()         { *m = GetPodResourceRequest{} }
func (m *GetPodResourceRequest) String() string { return proto.CompactTextString(m) }
func (*GetPodResourceRequest) ProtoMessage()    {}
func (*GetPodResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{14}
}

func (m *GetPodResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPodResourceRequest.Unmarshal(m, b)
}
func (m *GetPodResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPodResourceRequest.Marshal(b, m, deterministic)
}
func (m *GetPodResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPodResourceRequest.Merge(m, src)
}
func (m *GetPodResourceRequest) XXX_Size() int {
	return xxx_messageInfo_GetPodResourceRequest.Size(m)
}
func (m *GetPodResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPodResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPodResourceRequest proto.InternalMessageInfo

func (m *GetPodResourceRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetPodResourceRequest) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

func (m *GetPodResourceRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type GetPodResourceResponse struct {
	Pod                  *PodResource   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	BaseResp             *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetPodResourceResponse) Reset()         { *m = GetPodResourceResponse{} }
func (m *GetPodResourceResponse) String() string { return proto.CompactTextString(m) }
func (*GetPodResourceResponse) ProtoMessage()    {}
func (*GetPodResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{15}
}

func (m *GetPodResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPodResourceResponse.Unmarshal(m, b)
}
func (m *GetPodResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPodResourceResponse.Marshal(b, m, deterministic)
}
func (m *GetPodResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPodResourceResponse.Merge(m, src)
}
func (m *GetPodResourceResponse) XXX_Size() int {
	return xxx_messageInfo_GetPodResourceResponse.Size(m)
}
func (m *GetPodResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPodResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPodResourceResponse proto.InternalMessageInfo

func (m *GetPodResourceResponse) GetPod() *PodResource {
	if m != nil {
		return m.Pod
	}
	return nil
}

func (m *GetPodResourceResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetAlivePodRequest struct {
	Kind                 string     `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Base                 *base.Base `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAlivePodRequest) Reset()         { *m = GetAlivePodRequest{} }
func (m *GetAlivePodRequest) String() string { return proto.CompactTextString(m) }
func (*GetAlivePodRequest) ProtoMessage()    {}
func (*GetAlivePodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{16}
}

func (m *GetAlivePodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlivePodRequest.Unmarshal(m, b)
}
func (m *GetAlivePodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlivePodRequest.Marshal(b, m, deterministic)
}
func (m *GetAlivePodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlivePodRequest.Merge(m, src)
}
func (m *GetAlivePodRequest) XXX_Size() int {
	return xxx_messageInfo_GetAlivePodRequest.Size(m)
}
func (m *GetAlivePodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlivePodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlivePodRequest proto.InternalMessageInfo

func (m *GetAlivePodRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GetAlivePodRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type GetAlivePodResponse struct {
	Info                 map[string]string `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BaseResp             *base.BaseResp    `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAlivePodResponse) Reset()         { *m = GetAlivePodResponse{} }
func (m *GetAlivePodResponse) String() string { return proto.CompactTextString(m) }
func (*GetAlivePodResponse) ProtoMessage()    {}
func (*GetAlivePodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{17}
}

func (m *GetAlivePodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAlivePodResponse.Unmarshal(m, b)
}
func (m *GetAlivePodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAlivePodResponse.Marshal(b, m, deterministic)
}
func (m *GetAlivePodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAlivePodResponse.Merge(m, src)
}
func (m *GetAlivePodResponse) XXX_Size() int {
	return xxx_messageInfo_GetAlivePodResponse.Size(m)
}
func (m *GetAlivePodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAlivePodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAlivePodResponse proto.InternalMessageInfo

func (m *GetAlivePodResponse) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetAlivePodResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type PutStorageUtilRequest struct {
	PodName              string     `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	StorageUtil          string     `protobuf:"bytes,2,opt,name=storage_util,json=storageUtil,proto3" json:"storage_util,omitempty"`
	Base                 *base.Base `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutStorageUtilRequest) Reset()         { *m = PutStorageUtilRequest{} }
func (m *PutStorageUtilRequest) String() string { return proto.CompactTextString(m) }
func (*PutStorageUtilRequest) ProtoMessage()    {}
func (*PutStorageUtilRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{18}
}

func (m *PutStorageUtilRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutStorageUtilRequest.Unmarshal(m, b)
}
func (m *PutStorageUtilRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutStorageUtilRequest.Marshal(b, m, deterministic)
}
func (m *PutStorageUtilRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutStorageUtilRequest.Merge(m, src)
}
func (m *PutStorageUtilRequest) XXX_Size() int {
	return xxx_messageInfo_PutStorageUtilRequest.Size(m)
}
func (m *PutStorageUtilRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutStorageUtilRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutStorageUtilRequest proto.InternalMessageInfo

func (m *PutStorageUtilRequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *PutStorageUtilRequest) GetStorageUtil() string {
	if m != nil {
		return m.StorageUtil
	}
	return ""
}

func (m *PutStorageUtilRequest) GetBase() *base.Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type PutStorageUtilResponse struct {
	BaseResp             *base.BaseResp `protobuf:"bytes,255,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PutStorageUtilResponse) Reset()         { *m = PutStorageUtilResponse{} }
func (m *PutStorageUtilResponse) String() string { return proto.CompactTextString(m) }
func (*PutStorageUtilResponse) ProtoMessage()    {}
func (*PutStorageUtilResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b30a5d99d91ba1a, []int{19}
}

func (m *PutStorageUtilResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutStorageUtilResponse.Unmarshal(m, b)
}
func (m *PutStorageUtilResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutStorageUtilResponse.Marshal(b, m, deterministic)
}
func (m *PutStorageUtilResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutStorageUtilResponse.Merge(m, src)
}
func (m *PutStorageUtilResponse) XXX_Size() int {
	return xxx_messageInfo_PutStorageUtilResponse.Size(m)
}
func (m *PutStorageUtilResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutStorageUtilResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutStorageUtilResponse proto.InternalMessageInfo

func (m *PutStorageUtilResponse) GetBaseResp() *base.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func init() {
	proto.RegisterType((*Storage)(nil), "cdpb.Storage")
	proto.RegisterMapType((map[string]int64)(nil), "cdpb.Storage.ResourceEntry")
	proto.RegisterType((*Node)(nil), "cdpb.Node")
	proto.RegisterType((*PodResource)(nil), "cdpb.PodResource")
	proto.RegisterMapType((map[string]int64)(nil), "cdpb.PodResource.RequestResourceEntry")
	proto.RegisterType((*Volume)(nil), "cdpb.Volume")
	proto.RegisterType((*PutNodeStorageRequest)(nil), "cdpb.PutNodeStorageRequest")
	proto.RegisterType((*PutNodeStorageResponse)(nil), "cdpb.PutNodeStorageResponse")
	proto.RegisterType((*GetNodeStorageRequest)(nil), "cdpb.GetNodeStorageRequest")
	proto.RegisterType((*GetNodeStorageResponse)(nil), "cdpb.GetNodeStorageResponse")
	proto.RegisterMapType((map[string]*Node)(nil), "cdpb.GetNodeStorageResponse.NodesEntry")
	proto.RegisterType((*PutPodResourceRequest)(nil), "cdpb.PutPodResourceRequest")
	proto.RegisterType((*PutPodResourceResponse)(nil), "cdpb.PutPodResourceResponse")
	proto.RegisterType((*PutVolumeRequest)(nil), "cdpb.PutVolumeRequest")
	proto.RegisterType((*PutVolumeResponse)(nil), "cdpb.PutVolumeResponse")
	proto.RegisterType((*GetVolumeRequest)(nil), "cdpb.GetVolumeRequest")
	proto.RegisterType((*GetVolumeResponse)(nil), "cdpb.GetVolumeResponse")
	proto.RegisterType((*GetPodResourceRequest)(nil), "cdpb.GetPodResourceRequest")
	proto.RegisterType((*GetPodResourceResponse)(nil), "cdpb.GetPodResourceResponse")
	proto.RegisterType((*GetAlivePodRequest)(nil), "cdpb.GetAlivePodRequest")
	proto.RegisterType((*GetAlivePodResponse)(nil), "cdpb.GetAlivePodResponse")
	proto.RegisterMapType((map[string]string)(nil), "cdpb.GetAlivePodResponse.InfoEntry")
	proto.RegisterType((*PutStorageUtilRequest)(nil), "cdpb.PutStorageUtilRequest")
	proto.RegisterType((*PutStorageUtilResponse)(nil), "cdpb.PutStorageUtilResponse")
}

func init() { proto.RegisterFile("cdpb.proto", fileDescriptor_2b30a5d99d91ba1a) }

var fileDescriptor_2b30a5d99d91ba1a = []byte{
	// 949 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0x4b, 0x6f, 0xe3, 0x54,
	0x14, 0x96, 0x13, 0xe7, 0x75, 0x32, 0x0d, 0xe9, 0x65, 0xa6, 0x78, 0xc2, 0x68, 0xa6, 0x93, 0x01,
	0xa6, 0x0b, 0x94, 0x4a, 0x61, 0x51, 0xc4, 0x63, 0xd1, 0xf0, 0x88, 0xaa, 0x4a, 0x55, 0x30, 0x82,
	0x05, 0x9b, 0xe0, 0xd8, 0xb7, 0xa9, 0x89, 0xe3, 0x6b, 0xfc, 0x88, 0x28, 0x6c, 0xd8, 0xf1, 0x5b,
	0xd8, 0x22, 0xb1, 0xe3, 0x1f, 0x20, 0xf1, 0x97, 0x40, 0xf7, 0x65, 0x5f, 0x27, 0x37, 0x24, 0xe9,
	0xaa, 0x37, 0xe7, 0xdc, 0x73, 0xce, 0xf7, 0x9d, 0xd7, 0x75, 0x01, 0x5c, 0x2f, 0x9a, 0x0d, 0xa2,
	0x98, 0xa4, 0x04, 0x99, 0xf4, 0xdc, 0x83, 0x99, 0x93, 0x60, 0x2e, 0xe9, 0xff, 0x6e, 0x40, 0xe3,
	0xeb, 0x94, 0xc4, 0xce, 0x1c, 0xa3, 0xc7, 0x50, 0x0b, 0xf0, 0x0a, 0x07, 0x96, 0x71, 0x6a, 0x9c,
	0xb5, 0x6c, 0xfe, 0x03, 0x21, 0x30, 0x43, 0x67, 0x89, 0xad, 0x0a, 0x13, 0xb2, 0x33, 0xba, 0x80,
	0x66, 0x8c, 0x13, 0x92, 0xc5, 0x2e, 0xb6, 0xaa, 0xa7, 0xd5, 0xb3, 0xf6, 0xf0, 0xed, 0x01, 0x0b,
	0x23, 0x5c, 0x0d, 0x6c, 0xa1, 0xfd, 0x22, 0x4c, 0xe3, 0x7b, 0x3b, 0xbf, 0xdc, 0xfb, 0x18, 0x8e,
	0x4a, 0x2a, 0xd4, 0x85, 0xea, 0x02, 0xdf, 0x8b, 0x88, 0xf4, 0x48, 0x51, 0xac, 0x9c, 0x20, 0xe3,
	0x01, 0xab, 0x36, 0xff, 0xf1, 0x51, 0xe5, 0x43, 0xa3, 0x7f, 0x0e, 0xe6, 0x0d, 0xf1, 0x30, 0x7a,
	0x0d, 0x8d, 0x84, 0xc7, 0xb1, 0x0c, 0x16, 0xfc, 0xa8, 0x14, 0xdc, 0x96, 0xda, 0xfe, 0x5f, 0x15,
	0x68, 0x4f, 0x88, 0x27, 0x23, 0xe6, 0x54, 0x0c, 0x85, 0xca, 0x33, 0x68, 0xd1, 0xbf, 0x49, 0xe4,
	0xb8, 0x92, 0x63, 0x21, 0x60, 0x16, 0xc4, 0xa3, 0x24, 0xb9, 0x05, 0x0d, 0xdf, 0x83, 0xa6, 0x47,
	0xdc, 0x05, 0x8e, 0xaf, 0x3c, 0xcb, 0x64, 0xf2, 0xfc, 0x37, 0x7a, 0x0e, 0xe0, 0xce, 0x63, 0x92,
	0x45, 0x13, 0x27, 0xbd, 0xb3, 0x6a, 0x4c, 0xab, 0x48, 0xd0, 0x57, 0xd0, 0x8d, 0xf1, 0x8f, 0x19,
	0x4e, 0xd2, 0x69, 0x9e, 0xc0, 0x3a, 0xe3, 0xf0, 0x1e, 0xe7, 0xa0, 0xc0, 0x1d, 0xd8, 0xfc, 0x66,
	0x39, 0x97, 0x6f, 0xc4, 0x65, 0x69, 0x51, 0xb5, 0x86, 0x52, 0xb5, 0xde, 0x08, 0x1e, 0xeb, 0xcc,
	0x0f, 0xca, 0xf7, 0x1f, 0x06, 0xd4, 0xbf, 0x25, 0x41, 0xb6, 0xd4, 0x67, 0xee, 0x25, 0x3c, 0x5a,
	0x31, 0xed, 0x94, 0xf1, 0x13, 0xc9, 0x6b, 0x73, 0xd9, 0x98, 0x8a, 0xa8, 0x59, 0x96, 0xf9, 0x9e,
	0x4c, 0x1f, 0x3d, 0x53, 0x04, 0x4b, 0xe7, 0x07, 0x91, 0x39, 0x7a, 0x64, 0x12, 0x3f, 0x14, 0xd9,
	0xa2, 0x47, 0xf4, 0x2e, 0x74, 0x02, 0x32, 0xf7, 0x5d, 0x27, 0x98, 0x72, 0x77, 0x56, 0x9d, 0x29,
	0x8f, 0x84, 0xb4, 0x40, 0x95, 0xf8, 0x3f, 0x63, 0xc6, 0xbc, 0x66, 0xb3, 0x73, 0xff, 0x57, 0x03,
	0x9e, 0x4c, 0xb2, 0x94, 0x36, 0x8a, 0xec, 0x07, 0x9e, 0x07, 0x2d, 0x07, 0x04, 0xe6, 0xc2, 0x0f,
	0x3d, 0xd9, 0xdc, 0xf4, 0x8c, 0x9e, 0x2b, 0x35, 0x6f, 0x0f, 0x81, 0xd7, 0x85, 0xfa, 0x13, 0xf5,
	0x7f, 0x01, 0x26, 0x1d, 0x20, 0xeb, 0x5f, 0x43, 0x5c, 0x60, 0xe3, 0x34, 0x72, 0x12, 0x6c, 0x33,
	0x45, 0xff, 0x4b, 0x38, 0x59, 0x47, 0x90, 0x44, 0x24, 0x4c, 0x30, 0x7a, 0x1f, 0x5a, 0xf4, 0x06,
	0xad, 0x7d, 0x24, 0xed, 0x3b, 0x8a, 0x3d, 0x4e, 0x22, 0xbb, 0x39, 0x13, 0xa7, 0xfe, 0xf7, 0xf0,
	0x64, 0x8c, 0xb7, 0x30, 0x61, 0xa8, 0x0d, 0x05, 0xb5, 0xec, 0xd4, 0x8a, 0xd2, 0xa9, 0x3b, 0x91,
	0xfe, 0x6d, 0xc0, 0xc9, 0x7a, 0x08, 0x01, 0xf5, 0x53, 0xa8, 0x51, 0x1f, 0x89, 0x18, 0xb1, 0xd7,
	0x3c, 0x0d, 0xfa, 0xcb, 0x2c, 0x3b, 0x09, 0xef, 0x4f, 0x6e, 0x75, 0x18, 0xd3, 0xde, 0xe7, 0x00,
	0x85, 0x0b, 0x4d, 0x8f, 0x9e, 0xaa, 0x3d, 0x5a, 0xae, 0x89, 0xd2, 0xaf, 0xbf, 0xb0, 0xca, 0x2b,
	0x13, 0x24, 0xf3, 0xf5, 0x0a, 0xaa, 0x11, 0xe1, 0xe9, 0x6a, 0x0f, 0x8f, 0x37, 0x06, 0xcd, 0xa6,
	0x5a, 0xba, 0x08, 0x48, 0x84, 0x63, 0x27, 0xf5, 0x49, 0xc8, 0xe2, 0xd4, 0xec, 0x42, 0xb0, 0x6f,
	0xd1, 0x4b, 0xc1, 0x1f, 0x54, 0xf4, 0xdf, 0x0c, 0xe8, 0x4e, 0xb2, 0x94, 0x77, 0xb8, 0x24, 0xf0,
	0x0e, 0xd4, 0xc5, 0x1c, 0x70, 0xf3, 0x47, 0x9c, 0x83, 0xb8, 0x24, 0x74, 0xa8, 0x03, 0x95, 0x68,
	0x25, 0x1a, 0xa0, 0x12, 0xad, 0xca, 0x8c, 0xaa, 0x07, 0x33, 0xba, 0x84, 0x63, 0x05, 0xc8, 0x83,
	0xc8, 0x60, 0xe8, 0x8e, 0xf1, 0x1a, 0x97, 0xd2, 0xc2, 0x35, 0x74, 0x0b, 0x77, 0xfd, 0xb5, 0xd9,
	0x89, 0x74, 0x0e, 0xc7, 0x4a, 0x18, 0x81, 0x74, 0xbf, 0x9c, 0x1d, 0xc6, 0xe7, 0x8e, 0x4d, 0xa4,
	0xa6, 0xc3, 0xfe, 0x9f, 0x54, 0x97, 0xf7, 0x1f, 0xe7, 0xc4, 0x9a, 0x6d, 0x27, 0xa5, 0x05, 0x1b,
	0x4c, 0x5d, 0x3b, 0xed, 0xd5, 0xcc, 0x87, 0xd1, 0xba, 0x02, 0x34, 0xc6, 0xe9, 0x65, 0xe0, 0xaf,
	0x30, 0xf3, 0xb4, 0x7d, 0xcb, 0xec, 0xc4, 0xfd, 0xa7, 0x01, 0x6f, 0x96, 0x7c, 0x09, 0xd4, 0x17,
	0x60, 0xfa, 0xe1, 0x2d, 0x11, 0xdb, 0xe4, 0x55, 0xbe, 0x4d, 0xd6, 0x2f, 0x0e, 0xae, 0xc2, 0x5b,
	0xc2, 0x37, 0x09, 0x33, 0x38, 0x70, 0x91, 0x5c, 0x40, 0x2b, 0x77, 0xb0, 0xeb, 0xad, 0x6b, 0xa9,
	0xbb, 0x63, 0xc5, 0x76, 0x87, 0xd8, 0x6b, 0xdf, 0xa4, 0x7e, 0x20, 0xb3, 0xf0, 0x14, 0x9a, 0x11,
	0xf1, 0xa6, 0xca, 0xcb, 0xd1, 0x88, 0x88, 0x77, 0x23, 0x1e, 0x40, 0xf1, 0xa5, 0x31, 0xcd, 0x52,
	0x3f, 0x90, 0x0f, 0x60, 0x52, 0x38, 0xd9, 0x77, 0x6d, 0x94, 0xe2, 0x3e, 0x64, 0xd2, 0x86, 0xff,
	0x98, 0xd0, 0xfe, 0x8c, 0x90, 0xd8, 0xf3, 0x43, 0x27, 0x25, 0x31, 0xba, 0x86, 0x4e, 0xf9, 0x0d,
	0x42, 0xe2, 0x0b, 0x4d, 0xfb, 0x36, 0xf6, 0x9e, 0xe9, 0x95, 0x02, 0xca, 0x35, 0x74, 0xca, 0x8b,
	0x5f, 0x3a, 0xd3, 0x3e, 0x4f, 0xd2, 0xd9, 0x96, 0x87, 0x85, 0x23, 0x53, 0x3f, 0xcb, 0x0a, 0x64,
	0x9b, 0x93, 0xa5, 0x20, 0xd3, 0x0d, 0x03, 0x47, 0xa6, 0x71, 0xa6, 0x1d, 0x53, 0x05, 0x99, 0xce,
	0xd9, 0x27, 0xd0, 0xca, 0x17, 0x1e, 0x3a, 0xc9, 0xe3, 0x96, 0xd6, 0x57, 0xef, 0xad, 0x0d, 0x79,
	0x61, 0x9d, 0x2f, 0x21, 0x69, 0xbd, 0xbe, 0xfc, 0xa4, 0xf5, 0xe6, 0xb6, 0x1a, 0x41, 0x5b, 0x99,
	0x06, 0x64, 0x69, 0x06, 0x84, 0x7b, 0x78, 0xba, 0x75, 0x74, 0x44, 0x66, 0x95, 0x5e, 0x52, 0x32,
	0xbb, 0xd9, 0xd9, 0x4a, 0x66, 0x35, 0xed, 0x37, 0x7a, 0xf9, 0xdd, 0x8b, 0xb9, 0x9f, 0xde, 0x65,
	0xb3, 0x81, 0x4b, 0x96, 0xe7, 0x29, 0x59, 0x2e, 0x71, 0xf8, 0xd3, 0xb9, 0xeb, 0xb1, 0x7f, 0x1b,
	0xe8, 0xdf, 0xd9, 0xac, 0xce, 0xce, 0x1f, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xc4, 0x2c,
	0x7f, 0x62, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoordinatorClient interface {
	PutNodeStorage(ctx context.Context, in *PutNodeStorageRequest, opts ...grpc.CallOption) (*PutNodeStorageResponse, error)
	GetNodeStorage(ctx context.Context, in *GetNodeStorageRequest, opts ...grpc.CallOption) (*GetNodeStorageResponse, error)
	PutPodResource(ctx context.Context, in *PutPodResourceRequest, opts ...grpc.CallOption) (*PutPodResourceResponse, error)
	GetPodResource(ctx context.Context, in *GetPodResourceRequest, opts ...grpc.CallOption) (*GetPodResourceResponse, error)
	PutVolume(ctx context.Context, in *PutVolumeRequest, opts ...grpc.CallOption) (*PutVolumeResponse, error)
	GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error)
	GetAlivePod(ctx context.Context, in *GetAlivePodRequest, opts ...grpc.CallOption) (*GetAlivePodResponse, error)
	PutStorageUtil(ctx context.Context, in *PutStorageUtilRequest, opts ...grpc.CallOption) (*PutStorageUtilResponse, error)
}

type coordinatorClient struct {
	cc *grpc.ClientConn
}

func NewCoordinatorClient(cc *grpc.ClientConn) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) PutNodeStorage(ctx context.Context, in *PutNodeStorageRequest, opts ...grpc.CallOption) (*PutNodeStorageResponse, error) {
	out := new(PutNodeStorageResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/PutNodeStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) GetNodeStorage(ctx context.Context, in *GetNodeStorageRequest, opts ...grpc.CallOption) (*GetNodeStorageResponse, error) {
	out := new(GetNodeStorageResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/GetNodeStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) PutPodResource(ctx context.Context, in *PutPodResourceRequest, opts ...grpc.CallOption) (*PutPodResourceResponse, error) {
	out := new(PutPodResourceResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/PutPodResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) GetPodResource(ctx context.Context, in *GetPodResourceRequest, opts ...grpc.CallOption) (*GetPodResourceResponse, error) {
	out := new(GetPodResourceResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/GetPodResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) PutVolume(ctx context.Context, in *PutVolumeRequest, opts ...grpc.CallOption) (*PutVolumeResponse, error) {
	out := new(PutVolumeResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/PutVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) GetVolume(ctx context.Context, in *GetVolumeRequest, opts ...grpc.CallOption) (*GetVolumeResponse, error) {
	out := new(GetVolumeResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/GetVolume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) GetAlivePod(ctx context.Context, in *GetAlivePodRequest, opts ...grpc.CallOption) (*GetAlivePodResponse, error) {
	out := new(GetAlivePodResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/GetAlivePod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) PutStorageUtil(ctx context.Context, in *PutStorageUtilRequest, opts ...grpc.CallOption) (*PutStorageUtilResponse, error) {
	out := new(PutStorageUtilResponse)
	err := c.cc.Invoke(ctx, "/cdpb.Coordinator/PutStorageUtil", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
type CoordinatorServer interface {
	PutNodeStorage(context.Context, *PutNodeStorageRequest) (*PutNodeStorageResponse, error)
	GetNodeStorage(context.Context, *GetNodeStorageRequest) (*GetNodeStorageResponse, error)
	PutPodResource(context.Context, *PutPodResourceRequest) (*PutPodResourceResponse, error)
	GetPodResource(context.Context, *GetPodResourceRequest) (*GetPodResourceResponse, error)
	PutVolume(context.Context, *PutVolumeRequest) (*PutVolumeResponse, error)
	GetVolume(context.Context, *GetVolumeRequest) (*GetVolumeResponse, error)
	GetAlivePod(context.Context, *GetAlivePodRequest) (*GetAlivePodResponse, error)
	PutStorageUtil(context.Context, *PutStorageUtilRequest) (*PutStorageUtilResponse, error)
}

// UnimplementedCoordinatorServer can be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServer struct {
}

func (*UnimplementedCoordinatorServer) PutNodeStorage(ctx context.Context, req *PutNodeStorageRequest) (*PutNodeStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutNodeStorage not implemented")
}
func (*UnimplementedCoordinatorServer) GetNodeStorage(ctx context.Context, req *GetNodeStorageRequest) (*GetNodeStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeStorage not implemented")
}
func (*UnimplementedCoordinatorServer) PutPodResource(ctx context.Context, req *PutPodResourceRequest) (*PutPodResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPodResource not implemented")
}
func (*UnimplementedCoordinatorServer) GetPodResource(ctx context.Context, req *GetPodResourceRequest) (*GetPodResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodResource not implemented")
}
func (*UnimplementedCoordinatorServer) PutVolume(ctx context.Context, req *PutVolumeRequest) (*PutVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutVolume not implemented")
}
func (*UnimplementedCoordinatorServer) GetVolume(ctx context.Context, req *GetVolumeRequest) (*GetVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVolume not implemented")
}
func (*UnimplementedCoordinatorServer) GetAlivePod(ctx context.Context, req *GetAlivePodRequest) (*GetAlivePodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlivePod not implemented")
}
func (*UnimplementedCoordinatorServer) PutStorageUtil(ctx context.Context, req *PutStorageUtilRequest) (*PutStorageUtilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutStorageUtil not implemented")
}

func RegisterCoordinatorServer(s *grpc.Server, srv CoordinatorServer) {
	s.RegisterService(&_Coordinator_serviceDesc, srv)
}

func _Coordinator_PutNodeStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutNodeStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PutNodeStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/PutNodeStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PutNodeStorage(ctx, req.(*PutNodeStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_GetNodeStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetNodeStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/GetNodeStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetNodeStorage(ctx, req.(*GetNodeStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_PutPodResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPodResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PutPodResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/PutPodResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PutPodResource(ctx, req.(*PutPodResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_GetPodResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetPodResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/GetPodResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetPodResource(ctx, req.(*GetPodResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_PutVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PutVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/PutVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PutVolume(ctx, req.(*PutVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/GetVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetVolume(ctx, req.(*GetVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_GetAlivePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlivePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).GetAlivePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/GetAlivePod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).GetAlivePod(ctx, req.(*GetAlivePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_PutStorageUtil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutStorageUtilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).PutStorageUtil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cdpb.Coordinator/PutStorageUtil",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).PutStorageUtil(ctx, req.(*PutStorageUtilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coordinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cdpb.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutNodeStorage",
			Handler:    _Coordinator_PutNodeStorage_Handler,
		},
		{
			MethodName: "GetNodeStorage",
			Handler:    _Coordinator_GetNodeStorage_Handler,
		},
		{
			MethodName: "PutPodResource",
			Handler:    _Coordinator_PutPodResource_Handler,
		},
		{
			MethodName: "GetPodResource",
			Handler:    _Coordinator_GetPodResource_Handler,
		},
		{
			MethodName: "PutVolume",
			Handler:    _Coordinator_PutVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _Coordinator_GetVolume_Handler,
		},
		{
			MethodName: "GetAlivePod",
			Handler:    _Coordinator_GetAlivePod_Handler,
		},
		{
			MethodName: "PutStorageUtil",
			Handler:    _Coordinator_PutStorageUtil_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdpb.proto",
}
